# These templates are heavily inspired by the ones from trpc.io

blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: naingoolwin.astrio@gmail.com
    about: Feel free to reach out to me if you have questions