name: Feature Request
description: Suggest a new feature or enhancement
title: ""
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see?
      placeholder: A clear description of the feature...
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: "I would use this to..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered?
    validations:
      required: false

